### ISSUE TITLE
todo 종합 리뷰

### ISSUE THREAD

**Issue by abtinia** [naringst/Javascript-Todo#12]
$todoInput.id = `input-${todoIdx}`;
![8](https://github.com/naringst/Javascript-Todo/assets/115770904/7ff56726-c4bd-4481-b4f5-45d48ab707e5)

idx를 임의로 설정해서 필요한 요소들을 일괄 통제하는 부분이 인상 깊었습니다

![9](https://github.com/naringst/Javascript-Todo/assets/115770904/b104e8a2-e6d4-4ffe-ad55-d945aa1e0930)

localstorage도 덕분에 알아보기 편해서 좋았어요~

![10](https://github.com/naringst/Javascript-Todo/assets/115770904/938b98f3-bea2-44b5-9bd1-391bdc2e5f53)
화살표함수가 아니라 이런 식으로 함수를 선언해서? 사용하는 부분이 코드를 처음 보는 사람의 입장에서 더욱 편해서 좋았던 것 같습니다!

다만, 새로운 todo 추가, 수정, 삭제등과 같은 버튼에 마우스 커서를 올려뒀을 때, cursor : pointer이 주어졌다면 좀 더 직관성이 돋보이지 않았을까? 라는 생각이 들었습니다.

코드들이 대체적으로 자연스러운 순서의 흐름?에 따라 잘 짜여졌다는 느낌이 들어 위에서 아래로 한줄씩 읽어나가는 과정에서 큰 어려움이 없어서 좋았습니다!

**Comment by naringst** [comment]
제가 디테일한 부분은 놓쳤네요! 꼼꼼히 읽고 리뷰해주셔서 감사합니다!!!

**Comment by naringst** [comment]
제가 디테일한 부분은 놓쳤네요! 꼼꼼히 읽고 리뷰해주셔서 감사합니다!!!
