### ISSUE TITLE
요소 변수 이름 $ 적용

### ISSUE THREAD

**Issue by Sooamazing** [naringst/Javascript-Todo#2]
https://github.com/naringst/Javascript-Todo/blob/1ae64b7b8da2c6f95ff15028c0c232f655f2ccdf/main.js#L12

후반 강의를 보고서야 이게 관습(?)이라는 걸 알았던 전...  그저 감탄했습니다.... 
지켜서 사용해 주는 게 짱 좋아요!

**Comment by naringst** [comment]
저도 다른 강의에선가 듣고 참고했습니다 !! 감사합니다~!!!
