### ISSUE TITLE
id.split() 

### ISSUE THREAD

**Issue by Sooamazing** [naringst/Javascript-Todo#3]
https://github.com/naringst/Javascript-Todo/blob/1ae64b7b8da2c6f95ff15028c0c232f655f2ccdf/main.js#L65

문제 풀 때나 써 봤던... id.split를 실제로 구현할 때 사용하신 걸 보고 그저 감탄......

**Comment by naringst** [comment]
이걸 어찌해야하나 .. 하면서 구현했습니다 감사합니다!
