### ISSUE TITLE
저장, 수정, 수정 완료, 삭제 버튼

### ISSUE THREAD

**Issue by Sooamazing** [naringst/Javascript-Todo#5]
https://github.com/naringst/Javascript-Todo/blob/1ae64b7b8da2c6f95ff15028c0c232f655f2ccdf/main.js#L72

저 이렇게 하고 싶다 생각만 하고! 어려워 보여서 못했는데! 나리님이 구현하셔서 엄청 감탄했어요!!!
button 3개를 display:none 활용, 컨테이너 flex: space-between, 각 버튼 클릭 이벤트에 각 버튼 등장, 퇴장으로 하신 거 보고 간단하게 구현하셨구나 엄청 감탄했습니다...!!!!! 짱!!!

**Comment by naringst** [comment]
아직 많이 부족합니다!!! 감사합니다~!!
